apiVersion: v1
kind: Template
labels:
  template: osio-hypothesis-manager-api
metadata:
  name: osio-hypothesis-manager-api
  annotations:
    description: ${APP_NAME}
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
          - image: >-
              registry.devshift.net/fabric8-hypothesis/${IMAGE_NAME}:${IMAGE_TAG}
            imagePullPolicy: Always
            name: ${APP_NAME}
            env:
            - name: HYPOTHESIS_MANAGER_API_PORT
              value: ${HYPOTHESIS_MANAGER_API_PORT}
            - name: ROUTE_PATH
              value: ${ROUTE_PATH}
            - name: ROUTE_PREFIX
              value: ${ROUTE_PREFIX}
            ports:
            - containerPort: ${{HYPOTHESIS_MANAGER_API_PORT}}
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /manager/api/v1.0/readiness
                port: ${{HYPOTHESIS_MANAGER_API_PORT}}
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 10
            livenessProbe:
              httpGet:
                path: /manager/api/v1.0/liveness
                port: ${{HYPOTHESIS_MANAGER_API_PORT}}
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 10
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "1024Mi"
                cpu: "1000m"
            securityContext:
              privileged: false
      triggers:
        - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
      - name: ${APP_NAME}
        port: ${{HYPOTHESIS_MANAGER_API_PORT}}
        protocol: TCP
        targetPort: ${{HYPOTHESIS_MANAGER_API_PORT}}
    selector:
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
      template: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    path: /manager
    port:
      targetPort: ${APP_NAME}
    to:
      kind: Service
      name: ${APP_NAME}

parameters:
- name: HYPOTHESIS_MANAGER_API_PORT
  description: Port number that manager-api service will be exposed on.
  required: true
  value: "8888"
- name: HYPOTHESIS_MANAGER_SERVICE_TARGET_PORT
  description: Port number that manager-api service will map to.
  required: true
  value: "8888"
- name: HYPOTHESIS_MANAGER_API_HOSTNAME
  description: Parameterised hostname route for the manager-api service.
  required: false
- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"
- description: Name of the app
  displayName: Name of the app
  required: true
  name: APP_NAME
  value: "osio-hypothesis-manager-api"
- description: Image name
  displayName: Image name
  required: true
  name: IMAGE_NAME
  value: "osio-hypothesis-manager-api"
- description: Route path
  displayName: Route path
  required: true
  name: ROUTE_PATH
  value: "/manager"
- description: Route prefix
  displayName: Route prefix
  required: true
  name: ROUTE_PREFIX
  value: "/api/v1.0"
